### ISSUE TITLE
How to add diagonal text?

### ISSUE THREAD

**Issue by Gowtham029** [navjotdhanawat/dynamic-watermark#8]
I can add the watermark and adjust the position.

```
position: {
        logoX : 200,
        logoY : 200,
        logoHeight: 200,
        logoWidth: 200
    }
```

but, I want the text to be entered as diagonal.

Kindly someone help me to solve the problem.

Thanks,
Gowthamraj

**Comment by navjotdhanawat** [comment]
@Gowtham029 In this repo diagonal rotation need to add. Right now it doesnt support rotation.

But if you want to add diagonal rotation then just fork this repo and there is one method gm.rotation which will rotate it, please refer below link.
```
gm(source)
.fill(textColor)
.rotate(position.rotation)     //need to add this method
.drawText(logoX, logoY, text)
.fontSize(fontSize + 'px')
.write(destination, callback);
```

ref: (http://aheckmann.github.io/gm/docs.html#rotate)
